const NOT_FOUND_ERROR = 404;
const SERVER_ERROR = 500;
const BAD_REQUEST_ERROR = 400;
const LOGIN_ERROR = 401;
const EMAIL_ERROR = 409;

export {
  NOT_FOUND_ERROR, SERVER_ERROR, BAD_REQUEST_ERROR, LOGIN_ERROR, EMAIL_ERROR,
};
